// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingMapIconDescHandle : RemoteTableHandle<EventContext, BuildingMapIconDesc>
        {
            protected override string RemoteTableName => "building_map_icon_desc";

            public sealed class BuildingIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingMapIconDesc row) => row.BuildingId;

                public BuildingIdUniqueIndex(BuildingMapIconDescHandle table) : base(table) { }
            }

            public readonly BuildingIdUniqueIndex BuildingId;

            internal BuildingMapIconDescHandle(DbConnection conn) : base(conn)
            {
                BuildingId = new(this);
            }

            protected override object GetPrimaryKey(BuildingMapIconDesc row) => row.BuildingId;
        }

        public readonly BuildingMapIconDescHandle BuildingMapIconDesc;
    }

    public sealed class BuildingMapIconDescCols
    {
        public global::SpacetimeDB.Col<BuildingMapIconDesc, int> BuildingId { get; }
        public global::SpacetimeDB.Col<BuildingMapIconDesc, string> IconAddress { get; }
        public global::SpacetimeDB.Col<BuildingMapIconDesc, string> Title { get; }
        public global::SpacetimeDB.Col<BuildingMapIconDesc, string> Text { get; }

        public BuildingMapIconDescCols(string tableName)
        {
            BuildingId = new global::SpacetimeDB.Col<BuildingMapIconDesc, int>(tableName, "building_id");
            IconAddress = new global::SpacetimeDB.Col<BuildingMapIconDesc, string>(tableName, "icon_address");
            Title = new global::SpacetimeDB.Col<BuildingMapIconDesc, string>(tableName, "title");
            Text = new global::SpacetimeDB.Col<BuildingMapIconDesc, string>(tableName, "text");
        }
    }

    public sealed class BuildingMapIconDescIxCols
    {
        public global::SpacetimeDB.IxCol<BuildingMapIconDesc, int> BuildingId { get; }

        public BuildingMapIconDescIxCols(string tableName)
        {
            BuildingId = new global::SpacetimeDB.IxCol<BuildingMapIconDesc, int>(tableName, "building_id");
        }
    }
}
