// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GatedFeature
    {
        [DataMember(Name = "feature")]
        public string Feature;

        public GatedFeature(string Feature)
        {
            this.Feature = Feature;
        }

        public GatedFeature()
        {
            this.Feature = "";
        }
    }
}
