// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;

namespace BitCraft.Spacetime
{
    [SpacetimeDB.Type]
    public enum SkillType
    {
        None,
        Any,
        Forestry,
        Carpentry,
        Masonry,
        Mining,
        Smithing,
        Scholar,
        Leatherworking,
        Hunting,
        Tailoring,
        Farming,
        Fishing,
        Cooking,
        Foraging,
        Construction,
        Exploration,
        Taming,
        Slayer,
        Trading,
        LoreKeeper,
        Sailing,
        HexiteGathering,
    }
}
