// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TerraformRecipeDesc
    {
        [DataMember(Name = "difference")]
        public short Difference;
        [DataMember(Name = "actions_count")]
        public int ActionsCount;
        [DataMember(Name = "tool_requirement")]
        public ToolRequirement? ToolRequirement;
        [DataMember(Name = "stamina_per_action")]
        public float StaminaPerAction;
        [DataMember(Name = "time_per_action")]
        public float TimePerAction;
        [DataMember(Name = "tool_mesh_index")]
        public int ToolMeshIndex;
        [DataMember(Name = "recipe_performance_id")]
        public int RecipePerformanceId;
        [DataMember(Name = "output_item_stacks")]
        public System.Collections.Generic.List<ProbabilisticItemStack>? OutputItemStacks;

        public TerraformRecipeDesc(
            short Difference,
            int ActionsCount,
            ToolRequirement? ToolRequirement,
            float StaminaPerAction,
            float TimePerAction,
            int ToolMeshIndex,
            int RecipePerformanceId,
            System.Collections.Generic.List<ProbabilisticItemStack>? OutputItemStacks
        )
        {
            this.Difference = Difference;
            this.ActionsCount = ActionsCount;
            this.ToolRequirement = ToolRequirement;
            this.StaminaPerAction = StaminaPerAction;
            this.TimePerAction = TimePerAction;
            this.ToolMeshIndex = ToolMeshIndex;
            this.RecipePerformanceId = RecipePerformanceId;
            this.OutputItemStacks = OutputItemStacks;
        }

        public TerraformRecipeDesc()
        {
        }
    }
}
