// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminCleanSiegesHandler(ReducerEventContext ctx);
        public event AdminCleanSiegesHandler? OnAdminCleanSieges;

        public void AdminCleanSieges()
        {
            conn.InternalCallReducer(new Reducer.AdminCleanSieges());
        }

        public bool InvokeAdminCleanSieges(ReducerEventContext ctx, Reducer.AdminCleanSieges args)
        {
            if (OnAdminCleanSieges == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminCleanSieges(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminCleanSieges : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_clean_sieges";
        }
    }
}
