// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminPushEmpireRanksToRegionsHandler(ReducerEventContext ctx);
        public event AdminPushEmpireRanksToRegionsHandler? OnAdminPushEmpireRanksToRegions;

        public void AdminPushEmpireRanksToRegions()
        {
            conn.InternalCallReducer(new Reducer.AdminPushEmpireRanksToRegions());
        }

        public bool InvokeAdminPushEmpireRanksToRegions(ReducerEventContext ctx, Reducer.AdminPushEmpireRanksToRegions args)
        {
            if (OnAdminPushEmpireRanksToRegions == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminPushEmpireRanksToRegions(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminPushEmpireRanksToRegions : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_push_empire_ranks_to_regions";
        }
    }
}
