// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminUpdateGrantedHubItemStateHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity, BitCraft.Global.HubItemType itemType, int itemId, uint balance);
        public event AdminUpdateGrantedHubItemStateHandler? OnAdminUpdateGrantedHubItemState;

        public void AdminUpdateGrantedHubItemState(SpacetimeDB.Identity identity, BitCraft.Global.HubItemType itemType, int itemId, uint balance)
        {
            conn.InternalCallReducer(new Reducer.AdminUpdateGrantedHubItemState(identity, itemType, itemId, balance));
        }

        public bool InvokeAdminUpdateGrantedHubItemState(ReducerEventContext ctx, Reducer.AdminUpdateGrantedHubItemState args)
        {
            if (OnAdminUpdateGrantedHubItemState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminUpdateGrantedHubItemState(
                ctx,
                args.Identity,
                args.ItemType,
                args.ItemId,
                args.Balance
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminUpdateGrantedHubItemState : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;
            [DataMember(Name = "item_type")]
            public HubItemType ItemType;
            [DataMember(Name = "item_id")]
            public int ItemId;
            [DataMember(Name = "balance")]
            public uint Balance;

            public AdminUpdateGrantedHubItemState(
                SpacetimeDB.Identity Identity,
                HubItemType ItemType,
                int ItemId,
                uint Balance
            )
            {
                this.Identity = Identity;
                this.ItemType = ItemType;
                this.ItemId = ItemId;
                this.Balance = Balance;
            }

            public AdminUpdateGrantedHubItemState()
            {
            }

            string IReducerArgs.ReducerName => "admin_update_granted_hub_item_state";
        }
    }
}
