// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminUpdateRegionExplorationInfoHandler(ReducerEventContext ctx, byte regionId, bool countsTowardAchievements);
        public event AdminUpdateRegionExplorationInfoHandler? OnAdminUpdateRegionExplorationInfo;

        public void AdminUpdateRegionExplorationInfo(byte regionId, bool countsTowardAchievements)
        {
            conn.InternalCallReducer(new Reducer.AdminUpdateRegionExplorationInfo(regionId, countsTowardAchievements));
        }

        public bool InvokeAdminUpdateRegionExplorationInfo(ReducerEventContext ctx, Reducer.AdminUpdateRegionExplorationInfo args)
        {
            if (OnAdminUpdateRegionExplorationInfo == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminUpdateRegionExplorationInfo(
                ctx,
                args.RegionId,
                args.CountsTowardAchievements
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminUpdateRegionExplorationInfo : Reducer, IReducerArgs
        {
            [DataMember(Name = "region_id")]
            public byte RegionId;
            [DataMember(Name = "counts_toward_achievements")]
            public bool CountsTowardAchievements;

            public AdminUpdateRegionExplorationInfo(
                byte RegionId,
                bool CountsTowardAchievements
            )
            {
                this.RegionId = RegionId;
                this.CountsTowardAchievements = CountsTowardAchievements;
            }

            public AdminUpdateRegionExplorationInfo()
            {
            }

            string IReducerArgs.ReducerName => "admin_update_region_exploration_info";
        }
    }
}
