// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminUpdateEmpireRanksHandler(ReducerEventContext ctx);
        public event AdminUpdateEmpireRanksHandler? OnAdminUpdateEmpireRanks;

        public void AdminUpdateEmpireRanks()
        {
            conn.InternalCallReducer(new Reducer.AdminUpdateEmpireRanks());
        }

        public bool InvokeAdminUpdateEmpireRanks(ReducerEventContext ctx, Reducer.AdminUpdateEmpireRanks args)
        {
            if (OnAdminUpdateEmpireRanks == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminUpdateEmpireRanks(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminUpdateEmpireRanks : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_update_empire_ranks";
        }
    }
}
