// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveReplacementTextHandler(ReducerEventContext ctx, byte textType);
        public event AdminRemoveReplacementTextHandler? OnAdminRemoveReplacementText;

        public void AdminRemoveReplacementText(byte textType)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveReplacementText(textType));
        }

        public bool InvokeAdminRemoveReplacementText(ReducerEventContext ctx, Reducer.AdminRemoveReplacementText args)
        {
            if (OnAdminRemoveReplacementText == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveReplacementText(
                ctx,
                args.TextType
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveReplacementText : Reducer, IReducerArgs
        {
            [DataMember(Name = "text_type")]
            public byte TextType;

            public AdminRemoveReplacementText(byte TextType)
            {
                this.TextType = TextType;
            }

            public AdminRemoveReplacementText()
            {
            }

            string IReducerArgs.ReducerName => "admin_remove_replacement_text";
        }
    }
}
