// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChatPostTargetedMessageHandler(ReducerEventContext ctx, BitCraft.Global.PlayerChatPostMessageRequest request);
        public event ChatPostTargetedMessageHandler? OnChatPostTargetedMessage;

        public void ChatPostTargetedMessage(BitCraft.Global.PlayerChatPostMessageRequest request)
        {
            conn.InternalCallReducer(new Reducer.ChatPostTargetedMessage(request));
        }

        public bool InvokeChatPostTargetedMessage(ReducerEventContext ctx, Reducer.ChatPostTargetedMessage args)
        {
            if (OnChatPostTargetedMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChatPostTargetedMessage(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChatPostTargetedMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerChatPostMessageRequest Request;

            public ChatPostTargetedMessage(PlayerChatPostMessageRequest Request)
            {
                this.Request = Request;
            }

            public ChatPostTargetedMessage()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "chat_post_targeted_message";
        }
    }
}
