// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatShardsGrantHandler(ReducerEventContext ctx, BitCraft.Global.CheatShardsGrantRequest request);
        public event CheatShardsGrantHandler? OnCheatShardsGrant;

        public void CheatShardsGrant(BitCraft.Global.CheatShardsGrantRequest request)
        {
            conn.InternalCallReducer(new Reducer.CheatShardsGrant(request));
        }

        public bool InvokeCheatShardsGrant(ReducerEventContext ctx, Reducer.CheatShardsGrant args)
        {
            if (OnCheatShardsGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatShardsGrant(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatShardsGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public CheatShardsGrantRequest Request;

            public CheatShardsGrant(CheatShardsGrantRequest Request)
            {
                this.Request = Request;
            }

            public CheatShardsGrant()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "cheat_shards_grant";
        }
    }
}
