// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireTransferWatchtowerOwnershipHandler(ReducerEventContext ctx, ulong watchtowerEntityId, ulong targetEmpireEntityId);
        public event EmpireTransferWatchtowerOwnershipHandler? OnEmpireTransferWatchtowerOwnership;

        public void EmpireTransferWatchtowerOwnership(ulong watchtowerEntityId, ulong targetEmpireEntityId)
        {
            conn.InternalCallReducer(new Reducer.EmpireTransferWatchtowerOwnership(watchtowerEntityId, targetEmpireEntityId));
        }

        public bool InvokeEmpireTransferWatchtowerOwnership(ReducerEventContext ctx, Reducer.EmpireTransferWatchtowerOwnership args)
        {
            if (OnEmpireTransferWatchtowerOwnership == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireTransferWatchtowerOwnership(
                ctx,
                args.WatchtowerEntityId,
                args.TargetEmpireEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireTransferWatchtowerOwnership : Reducer, IReducerArgs
        {
            [DataMember(Name = "watchtower_entity_id")]
            public ulong WatchtowerEntityId;
            [DataMember(Name = "target_empire_entity_id")]
            public ulong TargetEmpireEntityId;

            public EmpireTransferWatchtowerOwnership(
                ulong WatchtowerEntityId,
                ulong TargetEmpireEntityId
            )
            {
                this.WatchtowerEntityId = WatchtowerEntityId;
                this.TargetEmpireEntityId = TargetEmpireEntityId;
            }

            public EmpireTransferWatchtowerOwnership()
            {
            }

            string IReducerArgs.ReducerName => "empire_transfer_watchtower_ownership";
        }
    }
}
