// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireSetRankTitleHandler(ReducerEventContext ctx, BitCraft.Global.EmpireSetRankTitleRequest request);
        public event EmpireSetRankTitleHandler? OnEmpireSetRankTitle;

        public void EmpireSetRankTitle(BitCraft.Global.EmpireSetRankTitleRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireSetRankTitle(request));
        }

        public bool InvokeEmpireSetRankTitle(ReducerEventContext ctx, Reducer.EmpireSetRankTitle args)
        {
            if (OnEmpireSetRankTitle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireSetRankTitle(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireSetRankTitle : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireSetRankTitleRequest Request;

            public EmpireSetRankTitle(EmpireSetRankTitleRequest Request)
            {
                this.Request = Request;
            }

            public EmpireSetRankTitle()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_set_rank_title";
        }
    }
}
