// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireLeaveHandler(ReducerEventContext ctx, BitCraft.Global.EmpireLeaveRequest request);
        public event EmpireLeaveHandler? OnEmpireLeave;

        public void EmpireLeave(BitCraft.Global.EmpireLeaveRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireLeave(request));
        }

        public bool InvokeEmpireLeave(ReducerEventContext ctx, Reducer.EmpireLeave args)
        {
            if (OnEmpireLeave == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireLeave(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireLeave : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireLeaveRequest Request;

            public EmpireLeave(EmpireLeaveRequest Request)
            {
                this.Request = Request;
            }

            public EmpireLeave()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_leave";
        }
    }
}
