// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireMarkForSiegeHandler(ReducerEventContext ctx, BitCraft.Global.EmpireMarkForSiegeRequest request);
        public event EmpireMarkForSiegeHandler? OnEmpireMarkForSiege;

        public void EmpireMarkForSiege(BitCraft.Global.EmpireMarkForSiegeRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireMarkForSiege(request));
        }

        public bool InvokeEmpireMarkForSiege(ReducerEventContext ctx, Reducer.EmpireMarkForSiege args)
        {
            if (OnEmpireMarkForSiege == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireMarkForSiege(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireMarkForSiege : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireMarkForSiegeRequest Request;

            public EmpireMarkForSiege(EmpireMarkForSiegeRequest Request)
            {
                this.Request = Request;
            }

            public EmpireMarkForSiege()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_mark_for_siege";
        }
    }
}
