// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpirePlayerJoinHandler(ReducerEventContext ctx, BitCraft.Global.EmpirePlayerJoinRequest request);
        public event EmpirePlayerJoinHandler? OnEmpirePlayerJoin;

        public void EmpirePlayerJoin(BitCraft.Global.EmpirePlayerJoinRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpirePlayerJoin(request));
        }

        public bool InvokeEmpirePlayerJoin(ReducerEventContext ctx, Reducer.EmpirePlayerJoin args)
        {
            if (OnEmpirePlayerJoin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpirePlayerJoin(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpirePlayerJoin : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpirePlayerJoinRequest Request;

            public EmpirePlayerJoin(EmpirePlayerJoinRequest Request)
            {
                this.Request = Request;
            }

            public EmpirePlayerJoin()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_player_join";
        }
    }
}
