// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireDismantleHandler(ReducerEventContext ctx, BitCraft.Global.EmpireDismantleRequest request);
        public event EmpireDismantleHandler? OnEmpireDismantle;

        public void EmpireDismantle(BitCraft.Global.EmpireDismantleRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireDismantle(request));
        }

        public bool InvokeEmpireDismantle(ReducerEventContext ctx, Reducer.EmpireDismantle args)
        {
            if (OnEmpireDismantle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireDismantle(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireDismantle : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireDismantleRequest Request;

            public EmpireDismantle(EmpireDismantleRequest Request)
            {
                this.Request = Request;
            }

            public EmpireDismantle()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_dismantle";
        }
    }
}
