// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportToolTypeDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ToolTypeDesc> records);
        public event ImportToolTypeDescHandler? OnImportToolTypeDesc;

        public void ImportToolTypeDesc(System.Collections.Generic.List<BitCraft.Global.ToolTypeDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportToolTypeDesc(records));
        }

        public bool InvokeImportToolTypeDesc(ReducerEventContext ctx, Reducer.ImportToolTypeDesc args)
        {
            if (OnImportToolTypeDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportToolTypeDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportToolTypeDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ToolTypeDesc> Records;

            public ImportToolTypeDesc(System.Collections.Generic.List<ToolTypeDesc> Records)
            {
                this.Records = Records;
            }

            public ImportToolTypeDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_tool_type_desc";
        }
    }
}
