// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportExperienceStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ExperienceState> records);
        public event ImportExperienceStateHandler? OnImportExperienceState;

        public void ImportExperienceState(System.Collections.Generic.List<BitCraft.Global.ExperienceState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportExperienceState(records));
        }

        public bool InvokeImportExperienceState(ReducerEventContext ctx, Reducer.ImportExperienceState args)
        {
            if (OnImportExperienceState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportExperienceState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportExperienceState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ExperienceState> Records;

            public ImportExperienceState(System.Collections.Generic.List<ExperienceState> Records)
            {
                this.Records = Records;
            }

            public ImportExperienceState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_experience_state";
        }
    }
}
