// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportEquipmentPresetStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.EquipmentPresetState> records);
        public event ImportEquipmentPresetStateHandler? OnImportEquipmentPresetState;

        public void ImportEquipmentPresetState(System.Collections.Generic.List<BitCraft.Global.EquipmentPresetState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportEquipmentPresetState(records));
        }

        public bool InvokeImportEquipmentPresetState(ReducerEventContext ctx, Reducer.ImportEquipmentPresetState args)
        {
            if (OnImportEquipmentPresetState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportEquipmentPresetState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportEquipmentPresetState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EquipmentPresetState> Records;

            public ImportEquipmentPresetState(System.Collections.Generic.List<EquipmentPresetState> Records)
            {
                this.Records = Records;
            }

            public ImportEquipmentPresetState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_equipment_preset_state";
        }
    }
}
