// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportRegionExplorationInfoHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.RegionExplorationInfo> records);
        public event ImportRegionExplorationInfoHandler? OnImportRegionExplorationInfo;

        public void ImportRegionExplorationInfo(System.Collections.Generic.List<BitCraft.Global.RegionExplorationInfo> records)
        {
            conn.InternalCallReducer(new Reducer.ImportRegionExplorationInfo(records));
        }

        public bool InvokeImportRegionExplorationInfo(ReducerEventContext ctx, Reducer.ImportRegionExplorationInfo args)
        {
            if (OnImportRegionExplorationInfo == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportRegionExplorationInfo(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportRegionExplorationInfo : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<RegionExplorationInfo> Records;

            public ImportRegionExplorationInfo(System.Collections.Generic.List<RegionExplorationInfo> Records)
            {
                this.Records = Records;
            }

            public ImportRegionExplorationInfo()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_region_exploration_info";
        }
    }
}
