// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportPlayerStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.PlayerState> records);
        public event ImportPlayerStateHandler? OnImportPlayerState;

        public void ImportPlayerState(System.Collections.Generic.List<BitCraft.Global.PlayerState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportPlayerState(records));
        }

        public bool InvokeImportPlayerState(ReducerEventContext ctx, Reducer.ImportPlayerState args)
        {
            if (OnImportPlayerState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportPlayerState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportPlayerState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<PlayerState> Records;

            public ImportPlayerState(System.Collections.Generic.List<PlayerState> Records)
            {
                this.Records = Records;
            }

            public ImportPlayerState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_player_state";
        }
    }
}
