// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportHealthStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.HealthState> records);
        public event ImportHealthStateHandler? OnImportHealthState;

        public void ImportHealthState(System.Collections.Generic.List<BitCraft.Global.HealthState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportHealthState(records));
        }

        public bool InvokeImportHealthState(ReducerEventContext ctx, Reducer.ImportHealthState args)
        {
            if (OnImportHealthState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportHealthState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportHealthState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<HealthState> Records;

            public ImportHealthState(System.Collections.Generic.List<HealthState> Records)
            {
                this.Records = Records;
            }

            public ImportHealthState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_health_state";
        }
    }
}
