// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportClimbRequirementDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ClimbRequirementDesc> records);
        public event ImportClimbRequirementDescHandler? OnImportClimbRequirementDesc;

        public void ImportClimbRequirementDesc(System.Collections.Generic.List<BitCraft.Global.ClimbRequirementDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportClimbRequirementDesc(records));
        }

        public bool InvokeImportClimbRequirementDesc(ReducerEventContext ctx, Reducer.ImportClimbRequirementDesc args)
        {
            if (OnImportClimbRequirementDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportClimbRequirementDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportClimbRequirementDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ClimbRequirementDesc> Records;

            public ImportClimbRequirementDesc(System.Collections.Generic.List<ClimbRequirementDesc> Records)
            {
                this.Records = Records;
            }

            public ImportClimbRequirementDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_climb_requirement_desc";
        }
    }
}
