// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportLootTableDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.LootTableDesc> records);
        public event ImportLootTableDescHandler? OnImportLootTableDesc;

        public void ImportLootTableDesc(System.Collections.Generic.List<BitCraft.Global.LootTableDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportLootTableDesc(records));
        }

        public bool InvokeImportLootTableDesc(ReducerEventContext ctx, Reducer.ImportLootTableDesc args)
        {
            if (OnImportLootTableDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportLootTableDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportLootTableDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<LootTableDesc> Records;

            public ImportLootTableDesc(System.Collections.Generic.List<LootTableDesc> Records)
            {
                this.Records = Records;
            }

            public ImportLootTableDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_loot_table_desc";
        }
    }
}
