// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportLootRarityDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.LootRarityDesc> records);
        public event ImportLootRarityDescHandler? OnImportLootRarityDesc;

        public void ImportLootRarityDesc(System.Collections.Generic.List<BitCraft.Global.LootRarityDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportLootRarityDesc(records));
        }

        public bool InvokeImportLootRarityDesc(ReducerEventContext ctx, Reducer.ImportLootRarityDesc args)
        {
            if (OnImportLootRarityDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportLootRarityDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportLootRarityDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<LootRarityDesc> Records;

            public ImportLootRarityDesc(System.Collections.Generic.List<LootRarityDesc> Records)
            {
                this.Records = Records;
            }

            public ImportLootRarityDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_loot_rarity_desc";
        }
    }
}
