// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportBuildingStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.BuildingState> records);
        public event ImportBuildingStateHandler? OnImportBuildingState;

        public void ImportBuildingState(System.Collections.Generic.List<BitCraft.Global.BuildingState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportBuildingState(records));
        }

        public bool InvokeImportBuildingState(ReducerEventContext ctx, Reducer.ImportBuildingState args)
        {
            if (OnImportBuildingState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportBuildingState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportBuildingState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<BuildingState> Records;

            public ImportBuildingState(System.Collections.Generic.List<BuildingState> Records)
            {
                this.Records = Records;
            }

            public ImportBuildingState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_building_state";
        }
    }
}
