// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportKnowledgeScrollDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.KnowledgeScrollDesc> records);
        public event ImportKnowledgeScrollDescHandler? OnImportKnowledgeScrollDesc;

        public void ImportKnowledgeScrollDesc(System.Collections.Generic.List<BitCraft.Global.KnowledgeScrollDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportKnowledgeScrollDesc(records));
        }

        public bool InvokeImportKnowledgeScrollDesc(ReducerEventContext ctx, Reducer.ImportKnowledgeScrollDesc args)
        {
            if (OnImportKnowledgeScrollDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportKnowledgeScrollDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportKnowledgeScrollDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<KnowledgeScrollDesc> Records;

            public ImportKnowledgeScrollDesc(System.Collections.Generic.List<KnowledgeScrollDesc> Records)
            {
                this.Records = Records;
            }

            public ImportKnowledgeScrollDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_knowledge_scroll_desc";
        }
    }
}
