// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportItemDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ItemDesc> records);
        public event ImportItemDescHandler? OnImportItemDesc;

        public void ImportItemDesc(System.Collections.Generic.List<BitCraft.Global.ItemDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportItemDesc(records));
        }

        public bool InvokeImportItemDesc(ReducerEventContext ctx, Reducer.ImportItemDesc args)
        {
            if (OnImportItemDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportItemDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportItemDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ItemDesc> Records;

            public ImportItemDesc(System.Collections.Generic.List<ItemDesc> Records)
            {
                this.Records = Records;
            }

            public ImportItemDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_item_desc";
        }
    }
}
