// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportSignedInPlayerStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.SignedInPlayerState> records);
        public event ImportSignedInPlayerStateHandler? OnImportSignedInPlayerState;

        public void ImportSignedInPlayerState(System.Collections.Generic.List<BitCraft.Global.SignedInPlayerState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportSignedInPlayerState(records));
        }

        public bool InvokeImportSignedInPlayerState(ReducerEventContext ctx, Reducer.ImportSignedInPlayerState args)
        {
            if (OnImportSignedInPlayerState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportSignedInPlayerState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportSignedInPlayerState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<SignedInPlayerState> Records;

            public ImportSignedInPlayerState(System.Collections.Generic.List<SignedInPlayerState> Records)
            {
                this.Records = Records;
            }

            public ImportSignedInPlayerState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_signed_in_player_state";
        }
    }
}
