// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetRoleForIdentityHandler(ReducerEventContext ctx, string identity, BitCraft.Global.Role role);
        public event SetRoleForIdentityHandler? OnSetRoleForIdentity;

        public void SetRoleForIdentity(string identity, BitCraft.Global.Role role)
        {
            conn.InternalCallReducer(new Reducer.SetRoleForIdentity(identity, role));
        }

        public bool InvokeSetRoleForIdentity(ReducerEventContext ctx, Reducer.SetRoleForIdentity args)
        {
            if (OnSetRoleForIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetRoleForIdentity(
                ctx,
                args.Identity,
                args.Role
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetRoleForIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;
            [DataMember(Name = "role")]
            public Role Role;

            public SetRoleForIdentity(
                string Identity,
                Role Role
            )
            {
                this.Identity = Identity;
                this.Role = Role;
            }

            public SetRoleForIdentity()
            {
                this.Identity = "";
            }

            string IReducerArgs.ReducerName => "set_role_for_identity";
        }
    }
}
