// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetVisibilityHandler(ReducerEventContext ctx, BitCraft.Global.VisibilityType visibility);
        public event SetVisibilityHandler? OnSetVisibility;

        public void SetVisibility(BitCraft.Global.VisibilityType visibility)
        {
            conn.InternalCallReducer(new Reducer.SetVisibility(visibility));
        }

        public bool InvokeSetVisibility(ReducerEventContext ctx, Reducer.SetVisibility args)
        {
            if (OnSetVisibility == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetVisibility(
                ctx,
                args.Visibility
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetVisibility : Reducer, IReducerArgs
        {
            [DataMember(Name = "visibility")]
            public VisibilityType Visibility;

            public SetVisibility(VisibilityType Visibility)
            {
                this.Visibility = Visibility;
            }

            public SetVisibility()
            {
            }

            string IReducerArgs.ReducerName => "set_visibility";
        }
    }
}
