// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageEquipmentDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.EquipmentDesc> records);
        public event StageEquipmentDescHandler? OnStageEquipmentDesc;

        public void StageEquipmentDesc(System.Collections.Generic.List<BitCraft.Global.EquipmentDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageEquipmentDesc(records));
        }

        public bool InvokeStageEquipmentDesc(ReducerEventContext ctx, Reducer.StageEquipmentDesc args)
        {
            if (OnStageEquipmentDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageEquipmentDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageEquipmentDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EquipmentDesc> Records;

            public StageEquipmentDesc(System.Collections.Generic.List<EquipmentDesc> Records)
            {
                this.Records = Records;
            }

            public StageEquipmentDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_equipment_desc";
        }
    }
}
