// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageTravelerTaskKnowledgeRequirementDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.TravelerTaskKnowledgeRequirementDesc> records);
        public event StageTravelerTaskKnowledgeRequirementDescHandler? OnStageTravelerTaskKnowledgeRequirementDesc;

        public void StageTravelerTaskKnowledgeRequirementDesc(System.Collections.Generic.List<BitCraft.Global.TravelerTaskKnowledgeRequirementDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageTravelerTaskKnowledgeRequirementDesc(records));
        }

        public bool InvokeStageTravelerTaskKnowledgeRequirementDesc(ReducerEventContext ctx, Reducer.StageTravelerTaskKnowledgeRequirementDesc args)
        {
            if (OnStageTravelerTaskKnowledgeRequirementDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageTravelerTaskKnowledgeRequirementDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageTravelerTaskKnowledgeRequirementDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<TravelerTaskKnowledgeRequirementDesc> Records;

            public StageTravelerTaskKnowledgeRequirementDesc(System.Collections.Generic.List<TravelerTaskKnowledgeRequirementDesc> Records)
            {
                this.Records = Records;
            }

            public StageTravelerTaskKnowledgeRequirementDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_traveler_task_knowledge_requirement_desc";
        }
    }
}
