// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StagePavingTileDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.PavingTileDesc> records);
        public event StagePavingTileDescHandler? OnStagePavingTileDesc;

        public void StagePavingTileDesc(System.Collections.Generic.List<BitCraft.Global.PavingTileDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StagePavingTileDesc(records));
        }

        public bool InvokeStagePavingTileDesc(ReducerEventContext ctx, Reducer.StagePavingTileDesc args)
        {
            if (OnStagePavingTileDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStagePavingTileDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StagePavingTileDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<PavingTileDesc> Records;

            public StagePavingTileDesc(System.Collections.Generic.List<PavingTileDesc> Records)
            {
                this.Records = Records;
            }

            public StagePavingTileDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_paving_tile_desc";
        }
    }
}
