// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageQuestChainDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.QuestChainDesc> records);
        public event StageQuestChainDescHandler? OnStageQuestChainDesc;

        public void StageQuestChainDesc(System.Collections.Generic.List<BitCraft.Global.QuestChainDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageQuestChainDesc(records));
        }

        public bool InvokeStageQuestChainDesc(ReducerEventContext ctx, Reducer.StageQuestChainDesc args)
        {
            if (OnStageQuestChainDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageQuestChainDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageQuestChainDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<QuestChainDesc> Records;

            public StageQuestChainDesc(System.Collections.Generic.List<QuestChainDesc> Records)
            {
                this.Records = Records;
            }

            public StageQuestChainDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_quest_chain_desc";
        }
    }
}
