// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageResourcePlacementRecipeDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ResourcePlacementRecipeDesc> records);
        public event StageResourcePlacementRecipeDescHandler? OnStageResourcePlacementRecipeDesc;

        public void StageResourcePlacementRecipeDesc(System.Collections.Generic.List<BitCraft.Global.ResourcePlacementRecipeDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageResourcePlacementRecipeDesc(records));
        }

        public bool InvokeStageResourcePlacementRecipeDesc(ReducerEventContext ctx, Reducer.StageResourcePlacementRecipeDesc args)
        {
            if (OnStageResourcePlacementRecipeDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageResourcePlacementRecipeDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageResourcePlacementRecipeDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ResourcePlacementRecipeDesc> Records;

            public StageResourcePlacementRecipeDesc(System.Collections.Generic.List<ResourcePlacementRecipeDesc> Records)
            {
                this.Records = Records;
            }

            public StageResourcePlacementRecipeDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_resource_placement_recipe_desc";
        }
    }
}
