// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageChestRarityDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Global.ChestRarityDesc> records);
        public event StageChestRarityDescHandler? OnStageChestRarityDesc;

        public void StageChestRarityDesc(System.Collections.Generic.List<BitCraft.Global.ChestRarityDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageChestRarityDesc(records));
        }

        public bool InvokeStageChestRarityDesc(ReducerEventContext ctx, Reducer.StageChestRarityDesc args)
        {
            if (OnStageChestRarityDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageChestRarityDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageChestRarityDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ChestRarityDesc> Records;

            public StageChestRarityDesc(System.Collections.Generic.List<ChestRarityDesc> Records)
            {
                this.Records = Records;
            }

            public StageChestRarityDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_chest_rarity_desc";
        }
    }
}
