// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminMigrateDeployableStateV2Handler(ReducerEventContext ctx);
        public event AdminMigrateDeployableStateV2Handler? OnAdminMigrateDeployableStateV2;

        public void AdminMigrateDeployableStateV2()
        {
            conn.InternalCallReducer(new Reducer.AdminMigrateDeployableStateV2());
        }

        public bool InvokeAdminMigrateDeployableStateV2(ReducerEventContext ctx, Reducer.AdminMigrateDeployableStateV2 args)
        {
            if (OnAdminMigrateDeployableStateV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminMigrateDeployableStateV2(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminMigrateDeployableStateV2 : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_migrate_deployable_state_v2";
        }
    }
}
