// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRenameClaimHandler(ReducerEventContext ctx, string claimName, string newName);
        public event AdminRenameClaimHandler? OnAdminRenameClaim;

        public void AdminRenameClaim(string claimName, string newName)
        {
            conn.InternalCallReducer(new Reducer.AdminRenameClaim(claimName, newName));
        }

        public bool InvokeAdminRenameClaim(ReducerEventContext ctx, Reducer.AdminRenameClaim args)
        {
            if (OnAdminRenameClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRenameClaim(
                ctx,
                args.ClaimName,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRenameClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "claim_name")]
            public string ClaimName;
            [DataMember(Name = "new_name")]
            public string NewName;

            public AdminRenameClaim(
                string ClaimName,
                string NewName
            )
            {
                this.ClaimName = ClaimName;
                this.NewName = NewName;
            }

            public AdminRenameClaim()
            {
                this.ClaimName = "";
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "admin_rename_claim";
        }
    }
}
