// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSetSignTextCoordHandler(ReducerEventContext ctx, BitCraft.Spacetime.OffsetCoordinatesSmallMessage coord, string newName);
        public event AdminSetSignTextCoordHandler? OnAdminSetSignTextCoord;

        public void AdminSetSignTextCoord(BitCraft.Spacetime.OffsetCoordinatesSmallMessage coord, string newName)
        {
            conn.InternalCallReducer(new Reducer.AdminSetSignTextCoord(coord, newName));
        }

        public bool InvokeAdminSetSignTextCoord(ReducerEventContext ctx, Reducer.AdminSetSignTextCoord args)
        {
            if (OnAdminSetSignTextCoord == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSetSignTextCoord(
                ctx,
                args.Coord,
                args.NewName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSetSignTextCoord : Reducer, IReducerArgs
        {
            [DataMember(Name = "coord")]
            public OffsetCoordinatesSmallMessage Coord;
            [DataMember(Name = "new_name")]
            public string NewName;

            public AdminSetSignTextCoord(
                OffsetCoordinatesSmallMessage Coord,
                string NewName
            )
            {
                this.Coord = Coord;
                this.NewName = NewName;
            }

            public AdminSetSignTextCoord()
            {
                this.Coord = new();
                this.NewName = "";
            }

            string IReducerArgs.ReducerName => "admin_set_sign_text_coord";
        }
    }
}
