// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminUpdateLightSourceStatesHandler(ReducerEventContext ctx);
        public event AdminUpdateLightSourceStatesHandler? OnAdminUpdateLightSourceStates;

        public void AdminUpdateLightSourceStates()
        {
            conn.InternalCallReducer(new Reducer.AdminUpdateLightSourceStates());
        }

        public bool InvokeAdminUpdateLightSourceStates(ReducerEventContext ctx, Reducer.AdminUpdateLightSourceStates args)
        {
            if (OnAdminUpdateLightSourceStates == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminUpdateLightSourceStates(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminUpdateLightSourceStates : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_update_light_source_states";
        }
    }
}
