// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSignOutHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity);
        public event AdminSignOutHandler? OnAdminSignOut;

        public void AdminSignOut(SpacetimeDB.Identity identity)
        {
            conn.InternalCallReducer(new Reducer.AdminSignOut(identity));
        }

        public bool InvokeAdminSignOut(ReducerEventContext ctx, Reducer.AdminSignOut args)
        {
            if (OnAdminSignOut == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSignOut(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSignOut : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;

            public AdminSignOut(SpacetimeDB.Identity Identity)
            {
                this.Identity = Identity;
            }

            public AdminSignOut()
            {
            }

            string IReducerArgs.ReducerName => "admin_sign_out";
        }
    }
}
