// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BuildingRepairStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerBuildingRepairRequest request);
        public event BuildingRepairStartHandler? OnBuildingRepairStart;

        public void BuildingRepairStart(BitCraft.Spacetime.PlayerBuildingRepairRequest request)
        {
            conn.InternalCallReducer(new Reducer.BuildingRepairStart(request));
        }

        public bool InvokeBuildingRepairStart(ReducerEventContext ctx, Reducer.BuildingRepairStart args)
        {
            if (OnBuildingRepairStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBuildingRepairStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BuildingRepairStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerBuildingRepairRequest Request;

            public BuildingRepairStart(PlayerBuildingRepairRequest Request)
            {
                this.Request = Request;
            }

            public BuildingRepairStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "building_repair_start";
        }
    }
}
