// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void BuildingSetNicknameHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerBuildingSetNicknameRequest request);
        public event BuildingSetNicknameHandler? OnBuildingSetNickname;

        public void BuildingSetNickname(BitCraft.Spacetime.PlayerBuildingSetNicknameRequest request)
        {
            conn.InternalCallReducer(new Reducer.BuildingSetNickname(request));
        }

        public bool InvokeBuildingSetNickname(ReducerEventContext ctx, Reducer.BuildingSetNickname args)
        {
            if (OnBuildingSetNickname == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnBuildingSetNickname(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class BuildingSetNickname : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerBuildingSetNicknameRequest Request;

            public BuildingSetNickname(PlayerBuildingSetNicknameRequest Request)
            {
                this.Request = Request;
            }

            public BuildingSetNickname()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "building_set_nickname";
        }
    }
}
