// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChatPostMessageHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerChatPostMessageRequest request);
        public event ChatPostMessageHandler? OnChatPostMessage;

        public void ChatPostMessage(BitCraft.Spacetime.PlayerChatPostMessageRequest request)
        {
            conn.InternalCallReducer(new Reducer.ChatPostMessage(request));
        }

        public bool InvokeChatPostMessage(ReducerEventContext ctx, Reducer.ChatPostMessage args)
        {
            if (OnChatPostMessage == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChatPostMessage(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChatPostMessage : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerChatPostMessageRequest Request;

            public ChatPostMessage(PlayerChatPostMessageRequest Request)
            {
                this.Request = Request;
            }

            public ChatPostMessage()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "chat_post_message";
        }
    }
}
