// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatWarpHandler(ReducerEventContext ctx, BitCraft.Spacetime.CheatWarpRequest request);
        public event CheatWarpHandler? OnCheatWarp;

        public void CheatWarp(BitCraft.Spacetime.CheatWarpRequest request)
        {
            conn.InternalCallReducer(new Reducer.CheatWarp(request));
        }

        public bool InvokeCheatWarp(ReducerEventContext ctx, Reducer.CheatWarp args)
        {
            if (OnCheatWarp == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatWarp(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatWarp : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public CheatWarpRequest Request;

            public CheatWarp(CheatWarpRequest Request)
            {
                this.Request = Request;
            }

            public CheatWarp()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "cheat_warp";
        }
    }
}
