// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimRemoveMemberHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimRemoveMemberRequest request);
        public event ClaimRemoveMemberHandler? OnClaimRemoveMember;

        public void ClaimRemoveMember(BitCraft.Spacetime.PlayerClaimRemoveMemberRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimRemoveMember(request));
        }

        public bool InvokeClaimRemoveMember(ReducerEventContext ctx, Reducer.ClaimRemoveMember args)
        {
            if (OnClaimRemoveMember == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimRemoveMember(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimRemoveMember : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimRemoveMemberRequest Request;

            public ClaimRemoveMember(PlayerClaimRemoveMemberRequest Request)
            {
                this.Request = Request;
            }

            public ClaimRemoveMember()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_remove_member";
        }
    }
}
