// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimTransferOwnershipHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimTransferOwnershipRequest request);
        public event ClaimTransferOwnershipHandler? OnClaimTransferOwnership;

        public void ClaimTransferOwnership(BitCraft.Spacetime.PlayerClaimTransferOwnershipRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimTransferOwnership(request));
        }

        public bool InvokeClaimTransferOwnership(ReducerEventContext ctx, Reducer.ClaimTransferOwnership args)
        {
            if (OnClaimTransferOwnership == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimTransferOwnership(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimTransferOwnership : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimTransferOwnershipRequest Request;

            public ClaimTransferOwnership(PlayerClaimTransferOwnershipRequest Request)
            {
                this.Request = Request;
            }

            public ClaimTransferOwnership()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_transfer_ownership";
        }
    }
}
