// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimTreasuryDepositHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimDepositToTreasuryRequest request);
        public event ClaimTreasuryDepositHandler? OnClaimTreasuryDeposit;

        public void ClaimTreasuryDeposit(BitCraft.Spacetime.PlayerClaimDepositToTreasuryRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimTreasuryDeposit(request));
        }

        public bool InvokeClaimTreasuryDeposit(ReducerEventContext ctx, Reducer.ClaimTreasuryDeposit args)
        {
            if (OnClaimTreasuryDeposit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimTreasuryDeposit(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimTreasuryDeposit : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimDepositToTreasuryRequest Request;

            public ClaimTreasuryDeposit(PlayerClaimDepositToTreasuryRequest Request)
            {
                this.Request = Request;
            }

            public ClaimTreasuryDeposit()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_treasury_deposit";
        }
    }
}
