// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimAddTileHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimAddTileRequest request);
        public event ClaimAddTileHandler? OnClaimAddTile;

        public void ClaimAddTile(BitCraft.Spacetime.PlayerClaimAddTileRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimAddTile(request));
        }

        public bool InvokeClaimAddTile(ReducerEventContext ctx, Reducer.ClaimAddTile args)
        {
            if (OnClaimAddTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimAddTile(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimAddTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimAddTileRequest Request;

            public ClaimAddTile(PlayerClaimAddTileRequest Request)
            {
                this.Request = Request;
            }

            public ClaimAddTile()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_add_tile";
        }
    }
}
