// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimAddRecruitmentHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimAddRecruitmentRequest request);
        public event ClaimAddRecruitmentHandler? OnClaimAddRecruitment;

        public void ClaimAddRecruitment(BitCraft.Spacetime.PlayerClaimAddRecruitmentRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimAddRecruitment(request));
        }

        public bool InvokeClaimAddRecruitment(ReducerEventContext ctx, Reducer.ClaimAddRecruitment args)
        {
            if (OnClaimAddRecruitment == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimAddRecruitment(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimAddRecruitment : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimAddRecruitmentRequest Request;

            public ClaimAddRecruitment(PlayerClaimAddRecruitmentRequest Request)
            {
                this.Request = Request;
            }

            public ClaimAddRecruitment()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_add_recruitment";
        }
    }
}
