// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimResupplyHandler(ReducerEventContext ctx, BitCraft.Spacetime.ClaimResupplyRequest request);
        public event ClaimResupplyHandler? OnClaimResupply;

        public void ClaimResupply(BitCraft.Spacetime.ClaimResupplyRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimResupply(request));
        }

        public bool InvokeClaimResupply(ReducerEventContext ctx, Reducer.ClaimResupply args)
        {
            if (OnClaimResupply == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimResupply(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimResupply : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public ClaimResupplyRequest Request;

            public ClaimResupply(ClaimResupplyRequest Request)
            {
                this.Request = Request;
            }

            public ClaimResupply()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_resupply";
        }
    }
}
