// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimWithdrawFromTreasuryHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClaimWithdrawFromTreasuryRequest request);
        public event ClaimWithdrawFromTreasuryHandler? OnClaimWithdrawFromTreasury;

        public void ClaimWithdrawFromTreasury(BitCraft.Spacetime.PlayerClaimWithdrawFromTreasuryRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimWithdrawFromTreasury(request));
        }

        public bool InvokeClaimWithdrawFromTreasury(ReducerEventContext ctx, Reducer.ClaimWithdrawFromTreasury args)
        {
            if (OnClaimWithdrawFromTreasury == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimWithdrawFromTreasury(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimWithdrawFromTreasury : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimWithdrawFromTreasuryRequest Request;

            public ClaimWithdrawFromTreasury(PlayerClaimWithdrawFromTreasuryRequest Request)
            {
                this.Request = Request;
            }

            public ClaimWithdrawFromTreasury()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_withdraw_from_treasury";
        }
    }
}
