// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CommitStagedStaticDataHandler(ReducerEventContext ctx);
        public event CommitStagedStaticDataHandler? OnCommitStagedStaticData;

        public void CommitStagedStaticData()
        {
            conn.InternalCallReducer(new Reducer.CommitStagedStaticData());
        }

        public bool InvokeCommitStagedStaticData(ReducerEventContext ctx, Reducer.CommitStagedStaticData args)
        {
            if (OnCommitStagedStaticData == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCommitStagedStaticData(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CommitStagedStaticData : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "commit_staged_static_data";
        }
    }
}
