// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CraftInitiateStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerCraftInitiateRequest request);
        public event CraftInitiateStartHandler? OnCraftInitiateStart;

        public void CraftInitiateStart(BitCraft.Spacetime.PlayerCraftInitiateRequest request)
        {
            conn.InternalCallReducer(new Reducer.CraftInitiateStart(request));
        }

        public bool InvokeCraftInitiateStart(ReducerEventContext ctx, Reducer.CraftInitiateStart args)
        {
            if (OnCraftInitiateStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCraftInitiateStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CraftInitiateStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerCraftInitiateRequest Request;

            public CraftInitiateStart(PlayerCraftInitiateRequest Request)
            {
                this.Request = Request;
            }

            public CraftInitiateStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "craft_initiate_start";
        }
    }
}
