// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeployableStoreStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.DeployableStoreRequest request);
        public event DeployableStoreStartHandler? OnDeployableStoreStart;

        public void DeployableStoreStart(BitCraft.Spacetime.DeployableStoreRequest request)
        {
            conn.InternalCallReducer(new Reducer.DeployableStoreStart(request));
        }

        public bool InvokeDeployableStoreStart(ReducerEventContext ctx, Reducer.DeployableStoreStart args)
        {
            if (OnDeployableStoreStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeployableStoreStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeployableStoreStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public DeployableStoreRequest Request;

            public DeployableStoreStart(DeployableStoreRequest Request)
            {
                this.Request = Request;
            }

            public DeployableStoreStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "deployable_store_start";
        }
    }
}
