// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeployableDismountHandler(ReducerEventContext ctx, BitCraft.Spacetime.OffsetCoordinatesFloat coordinates, BitCraft.Spacetime.OffsetCoordinatesFloat deployableCoordinates);
        public event DeployableDismountHandler? OnDeployableDismount;

        public void DeployableDismount(BitCraft.Spacetime.OffsetCoordinatesFloat coordinates, BitCraft.Spacetime.OffsetCoordinatesFloat deployableCoordinates)
        {
            conn.InternalCallReducer(new Reducer.DeployableDismount(coordinates, deployableCoordinates));
        }

        public bool InvokeDeployableDismount(ReducerEventContext ctx, Reducer.DeployableDismount args)
        {
            if (OnDeployableDismount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeployableDismount(
                ctx,
                args.Coordinates,
                args.DeployableCoordinates
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeployableDismount : Reducer, IReducerArgs
        {
            [DataMember(Name = "coordinates")]
            public OffsetCoordinatesFloat Coordinates;
            [DataMember(Name = "deployable_coordinates")]
            public OffsetCoordinatesFloat DeployableCoordinates;

            public DeployableDismount(
                OffsetCoordinatesFloat Coordinates,
                OffsetCoordinatesFloat DeployableCoordinates
            )
            {
                this.Coordinates = Coordinates;
                this.DeployableCoordinates = DeployableCoordinates;
            }

            public DeployableDismount()
            {
                this.Coordinates = new();
                this.DeployableCoordinates = new();
            }

            string IReducerArgs.ReducerName => "deployable_dismount";
        }
    }
}
