// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeployableFollowHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerDeployableMoveRequest request);
        public event DeployableFollowHandler? OnDeployableFollow;

        public void DeployableFollow(BitCraft.Spacetime.PlayerDeployableMoveRequest request)
        {
            conn.InternalCallReducer(new Reducer.DeployableFollow(request));
        }

        public bool InvokeDeployableFollow(ReducerEventContext ctx, Reducer.DeployableFollow args)
        {
            if (OnDeployableFollow == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeployableFollow(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeployableFollow : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerDeployableMoveRequest Request;

            public DeployableFollow(PlayerDeployableMoveRequest Request)
            {
                this.Request = Request;
            }

            public DeployableFollow()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "deployable_follow";
        }
    }
}
