// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverNpcHandler(ReducerEventContext ctx, int npcId);
        public event DiscoverNpcHandler? OnDiscoverNpc;

        public void DiscoverNpc(int npcId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverNpc(npcId));
        }

        public bool InvokeDiscoverNpc(ReducerEventContext ctx, Reducer.DiscoverNpc args)
        {
            if (OnDiscoverNpc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverNpc(
                ctx,
                args.NpcId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverNpc : Reducer, IReducerArgs
        {
            [DataMember(Name = "npc_id")]
            public int NpcId;

            public DiscoverNpc(int NpcId)
            {
                this.NpcId = NpcId;
            }

            public DiscoverNpc()
            {
            }

            string IReducerArgs.ReducerName => "discover_npc";
        }
    }
}
