// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverDeployableHandler(ReducerEventContext ctx, int deployableId);
        public event DiscoverDeployableHandler? OnDiscoverDeployable;

        public void DiscoverDeployable(int deployableId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverDeployable(deployableId));
        }

        public bool InvokeDiscoverDeployable(ReducerEventContext ctx, Reducer.DiscoverDeployable args)
        {
            if (OnDiscoverDeployable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverDeployable(
                ctx,
                args.DeployableId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverDeployable : Reducer, IReducerArgs
        {
            [DataMember(Name = "deployable_id")]
            public int DeployableId;

            public DiscoverDeployable(int DeployableId)
            {
                this.DeployableId = DeployableId;
            }

            public DiscoverDeployable()
            {
            }

            string IReducerArgs.ReducerName => "discover_deployable";
        }
    }
}
