// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverItemHandler(ReducerEventContext ctx, int itemId);
        public event DiscoverItemHandler? OnDiscoverItem;

        public void DiscoverItem(int itemId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverItem(itemId));
        }

        public bool InvokeDiscoverItem(ReducerEventContext ctx, Reducer.DiscoverItem args)
        {
            if (OnDiscoverItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverItem(
                ctx,
                args.ItemId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public int ItemId;

            public DiscoverItem(int ItemId)
            {
                this.ItemId = ItemId;
            }

            public DiscoverItem()
            {
            }

            string IReducerArgs.ReducerName => "discover_item";
        }
    }
}
