// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverClaimHandler(ReducerEventContext ctx, ulong claimEntityId);
        public event DiscoverClaimHandler? OnDiscoverClaim;

        public void DiscoverClaim(ulong claimEntityId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverClaim(claimEntityId));
        }

        public bool InvokeDiscoverClaim(ReducerEventContext ctx, Reducer.DiscoverClaim args)
        {
            if (OnDiscoverClaim == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverClaim(
                ctx,
                args.ClaimEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverClaim : Reducer, IReducerArgs
        {
            [DataMember(Name = "claim_entity_id")]
            public ulong ClaimEntityId;

            public DiscoverClaim(ulong ClaimEntityId)
            {
                this.ClaimEntityId = ClaimEntityId;
            }

            public DiscoverClaim()
            {
            }

            string IReducerArgs.ReducerName => "discover_claim";
        }
    }
}
