// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverResourceHandler(ReducerEventContext ctx, int resourceId);
        public event DiscoverResourceHandler? OnDiscoverResource;

        public void DiscoverResource(int resourceId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverResource(resourceId));
        }

        public bool InvokeDiscoverResource(ReducerEventContext ctx, Reducer.DiscoverResource args)
        {
            if (OnDiscoverResource == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverResource(
                ctx,
                args.ResourceId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverResource : Reducer, IReducerArgs
        {
            [DataMember(Name = "resource_id")]
            public int ResourceId;

            public DiscoverResource(int ResourceId)
            {
                this.ResourceId = ResourceId;
            }

            public DiscoverResource()
            {
            }

            string IReducerArgs.ReducerName => "discover_resource";
        }
    }
}
