// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverRuinsHandler(ReducerEventContext ctx, BitCraft.Spacetime.OffsetCoordinatesSmallMessage coordinates);
        public event DiscoverRuinsHandler? OnDiscoverRuins;

        public void DiscoverRuins(BitCraft.Spacetime.OffsetCoordinatesSmallMessage coordinates)
        {
            conn.InternalCallReducer(new Reducer.DiscoverRuins(coordinates));
        }

        public bool InvokeDiscoverRuins(ReducerEventContext ctx, Reducer.DiscoverRuins args)
        {
            if (OnDiscoverRuins == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverRuins(
                ctx,
                args.Coordinates
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverRuins : Reducer, IReducerArgs
        {
            [DataMember(Name = "coordinates")]
            public OffsetCoordinatesSmallMessage Coordinates;

            public DiscoverRuins(OffsetCoordinatesSmallMessage Coordinates)
            {
                this.Coordinates = Coordinates;
            }

            public DiscoverRuins()
            {
                this.Coordinates = new();
            }

            string IReducerArgs.ReducerName => "discover_ruins";
        }
    }
}
