// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverCollectibleHandler(ReducerEventContext ctx, int collectibleId);
        public event DiscoverCollectibleHandler? OnDiscoverCollectible;

        public void DiscoverCollectible(int collectibleId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverCollectible(collectibleId));
        }

        public bool InvokeDiscoverCollectible(ReducerEventContext ctx, Reducer.DiscoverCollectible args)
        {
            if (OnDiscoverCollectible == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverCollectible(
                ctx,
                args.CollectibleId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverCollectible : Reducer, IReducerArgs
        {
            [DataMember(Name = "collectible_id")]
            public int CollectibleId;

            public DiscoverCollectible(int CollectibleId)
            {
                this.CollectibleId = CollectibleId;
            }

            public DiscoverCollectible()
            {
            }

            string IReducerArgs.ReducerName => "discover_collectible";
        }
    }
}
