// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmoteHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerEmoteRequest request);
        public event EmoteHandler? OnEmote;

        public void Emote(BitCraft.Spacetime.PlayerEmoteRequest request)
        {
            conn.InternalCallReducer(new Reducer.Emote(request));
        }

        public bool InvokeEmote(ReducerEventContext ctx, Reducer.Emote args)
        {
            if (OnEmote == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmote(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Emote : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerEmoteRequest Request;

            public Emote(PlayerEmoteRequest Request)
            {
                this.Request = Request;
            }

            public Emote()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "emote";
        }
    }
}
