// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireQueueSuppliesHandler(ReducerEventContext ctx, BitCraft.Spacetime.EmpireQueueSuppliesRequest request);
        public event EmpireQueueSuppliesHandler? OnEmpireQueueSupplies;

        public void EmpireQueueSupplies(BitCraft.Spacetime.EmpireQueueSuppliesRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireQueueSupplies(request));
        }

        public bool InvokeEmpireQueueSupplies(ReducerEventContext ctx, Reducer.EmpireQueueSupplies args)
        {
            if (OnEmpireQueueSupplies == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireQueueSupplies(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireQueueSupplies : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireQueueSuppliesRequest Request;

            public EmpireQueueSupplies(EmpireQueueSuppliesRequest Request)
            {
                this.Request = Request;
            }

            public EmpireQueueSupplies()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_queue_supplies";
        }
    }
}
