// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireResupplyNodeHandler(ReducerEventContext ctx, BitCraft.Spacetime.EmpireResupplyNodeRequest request);
        public event EmpireResupplyNodeHandler? OnEmpireResupplyNode;

        public void EmpireResupplyNode(BitCraft.Spacetime.EmpireResupplyNodeRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireResupplyNode(request));
        }

        public bool InvokeEmpireResupplyNode(ReducerEventContext ctx, Reducer.EmpireResupplyNode args)
        {
            if (OnEmpireResupplyNode == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireResupplyNode(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireResupplyNode : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireResupplyNodeRequest Request;

            public EmpireResupplyNode(EmpireResupplyNodeRequest Request)
            {
                this.Request = Request;
            }

            public EmpireResupplyNode()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_resupply_node";
        }
    }
}
