// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireWithdrawItemHandler(ReducerEventContext ctx, int itemId, BitCraft.Spacetime.ItemType itemType, uint amount);
        public event EmpireWithdrawItemHandler? OnEmpireWithdrawItem;

        public void EmpireWithdrawItem(int itemId, BitCraft.Spacetime.ItemType itemType, uint amount)
        {
            conn.InternalCallReducer(new Reducer.EmpireWithdrawItem(itemId, itemType, amount));
        }

        public bool InvokeEmpireWithdrawItem(ReducerEventContext ctx, Reducer.EmpireWithdrawItem args)
        {
            if (OnEmpireWithdrawItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireWithdrawItem(
                ctx,
                args.ItemId,
                args.ItemType,
                args.Amount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireWithdrawItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "item_id")]
            public int ItemId;
            [DataMember(Name = "item_type")]
            public ItemType ItemType;
            [DataMember(Name = "amount")]
            public uint Amount;

            public EmpireWithdrawItem(
                int ItemId,
                ItemType ItemType,
                uint Amount
            )
            {
                this.ItemId = ItemId;
                this.ItemType = ItemType;
                this.Amount = Amount;
            }

            public EmpireWithdrawItem()
            {
            }

            string IReducerArgs.ReducerName => "empire_withdraw_item";
        }
    }
}
