// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnemyMoveHandler(ReducerEventContext ctx, BitCraft.Spacetime.EnemyMoveRequest request);
        public event EnemyMoveHandler? OnEnemyMove;

        public void EnemyMove(BitCraft.Spacetime.EnemyMoveRequest request)
        {
            conn.InternalCallReducer(new Reducer.EnemyMove(request));
        }

        public bool InvokeEnemyMove(ReducerEventContext ctx, Reducer.EnemyMove args)
        {
            if (OnEnemyMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnemyMove(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnemyMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EnemyMoveRequest Request;

            public EnemyMove(EnemyMoveRequest Request)
            {
                this.Request = Request;
            }

            public EnemyMove()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "enemy_move";
        }
    }
}
