// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnemySpawnLootHandler(ReducerEventContext ctx, BitCraft.Spacetime.EnemySpawnLootRequest request);
        public event EnemySpawnLootHandler? OnEnemySpawnLoot;

        public void EnemySpawnLoot(BitCraft.Spacetime.EnemySpawnLootRequest request)
        {
            conn.InternalCallReducer(new Reducer.EnemySpawnLoot(request));
        }

        public bool InvokeEnemySpawnLoot(ReducerEventContext ctx, Reducer.EnemySpawnLoot args)
        {
            if (OnEnemySpawnLoot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnemySpawnLoot(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnemySpawnLoot : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EnemySpawnLootRequest Request;

            public EnemySpawnLoot(EnemySpawnLootRequest Request)
            {
                this.Request = Request;
            }

            public EnemySpawnLoot()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "enemy_spawn_loot";
        }
    }
}
