// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportBuildingMapIconDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.BuildingMapIconDesc> records);
        public event ImportBuildingMapIconDescHandler? OnImportBuildingMapIconDesc;

        public void ImportBuildingMapIconDesc(System.Collections.Generic.List<BitCraft.Spacetime.BuildingMapIconDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportBuildingMapIconDesc(records));
        }

        public bool InvokeImportBuildingMapIconDesc(ReducerEventContext ctx, Reducer.ImportBuildingMapIconDesc args)
        {
            if (OnImportBuildingMapIconDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportBuildingMapIconDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportBuildingMapIconDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<BuildingMapIconDesc> Records;

            public ImportBuildingMapIconDesc(System.Collections.Generic.List<BuildingMapIconDesc> Records)
            {
                this.Records = Records;
            }

            public ImportBuildingMapIconDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_building_map_icon_desc";
        }
    }
}
