// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportInteriorCollapseTriggerStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.InteriorCollapseTriggerState> records);
        public event ImportInteriorCollapseTriggerStateHandler? OnImportInteriorCollapseTriggerState;

        public void ImportInteriorCollapseTriggerState(System.Collections.Generic.List<BitCraft.Spacetime.InteriorCollapseTriggerState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportInteriorCollapseTriggerState(records));
        }

        public bool InvokeImportInteriorCollapseTriggerState(ReducerEventContext ctx, Reducer.ImportInteriorCollapseTriggerState args)
        {
            if (OnImportInteriorCollapseTriggerState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportInteriorCollapseTriggerState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportInteriorCollapseTriggerState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<InteriorCollapseTriggerState> Records;

            public ImportInteriorCollapseTriggerState(System.Collections.Generic.List<InteriorCollapseTriggerState> Records)
            {
                this.Records = Records;
            }

            public ImportInteriorCollapseTriggerState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_interior_collapse_trigger_state";
        }
    }
}
