// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportEquipmentPresetKnowledgeDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.EquipmentPresetKnowledgeDesc> records);
        public event ImportEquipmentPresetKnowledgeDescHandler? OnImportEquipmentPresetKnowledgeDesc;

        public void ImportEquipmentPresetKnowledgeDesc(System.Collections.Generic.List<BitCraft.Spacetime.EquipmentPresetKnowledgeDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportEquipmentPresetKnowledgeDesc(records));
        }

        public bool InvokeImportEquipmentPresetKnowledgeDesc(ReducerEventContext ctx, Reducer.ImportEquipmentPresetKnowledgeDesc args)
        {
            if (OnImportEquipmentPresetKnowledgeDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportEquipmentPresetKnowledgeDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportEquipmentPresetKnowledgeDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EquipmentPresetKnowledgeDesc> Records;

            public ImportEquipmentPresetKnowledgeDesc(System.Collections.Generic.List<EquipmentPresetKnowledgeDesc> Records)
            {
                this.Records = Records;
            }

            public ImportEquipmentPresetKnowledgeDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_equipment_preset_knowledge_desc";
        }
    }
}
