// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportProspectingDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.ProspectingDesc> records);
        public event ImportProspectingDescHandler? OnImportProspectingDesc;

        public void ImportProspectingDesc(System.Collections.Generic.List<BitCraft.Spacetime.ProspectingDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportProspectingDesc(records));
        }

        public bool InvokeImportProspectingDesc(ReducerEventContext ctx, Reducer.ImportProspectingDesc args)
        {
            if (OnImportProspectingDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportProspectingDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportProspectingDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ProspectingDesc> Records;

            public ImportProspectingDesc(System.Collections.Generic.List<ProspectingDesc> Records)
            {
                this.Records = Records;
            }

            public ImportProspectingDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_prospecting_desc";
        }
    }
}
