// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportPlaceableInteractionDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.PlaceableInteractionDesc> records);
        public event ImportPlaceableInteractionDescHandler? OnImportPlaceableInteractionDesc;

        public void ImportPlaceableInteractionDesc(System.Collections.Generic.List<BitCraft.Spacetime.PlaceableInteractionDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportPlaceableInteractionDesc(records));
        }

        public bool InvokeImportPlaceableInteractionDesc(ReducerEventContext ctx, Reducer.ImportPlaceableInteractionDesc args)
        {
            if (OnImportPlaceableInteractionDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportPlaceableInteractionDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportPlaceableInteractionDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<PlaceableInteractionDesc> Records;

            public ImportPlaceableInteractionDesc(System.Collections.Generic.List<PlaceableInteractionDesc> Records)
            {
                this.Records = Records;
            }

            public ImportPlaceableInteractionDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_placeable_interaction_desc";
        }
    }
}
