// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportAlertDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.AlertDesc> records);
        public event ImportAlertDescHandler? OnImportAlertDesc;

        public void ImportAlertDesc(System.Collections.Generic.List<BitCraft.Spacetime.AlertDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportAlertDesc(records));
        }

        public bool InvokeImportAlertDesc(ReducerEventContext ctx, Reducer.ImportAlertDesc args)
        {
            if (OnImportAlertDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportAlertDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportAlertDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<AlertDesc> Records;

            public ImportAlertDesc(System.Collections.Generic.List<AlertDesc> Records)
            {
                this.Records = Records;
            }

            public ImportAlertDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_alert_desc";
        }
    }
}
