// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportResourcesLogHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.ResourcesLog> records);
        public event ImportResourcesLogHandler? OnImportResourcesLog;

        public void ImportResourcesLog(System.Collections.Generic.List<BitCraft.Spacetime.ResourcesLog> records)
        {
            conn.InternalCallReducer(new Reducer.ImportResourcesLog(records));
        }

        public bool InvokeImportResourcesLog(ReducerEventContext ctx, Reducer.ImportResourcesLog args)
        {
            if (OnImportResourcesLog == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportResourcesLog(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportResourcesLog : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ResourcesLog> Records;

            public ImportResourcesLog(System.Collections.Generic.List<ResourcesLog> Records)
            {
                this.Records = Records;
            }

            public ImportResourcesLog()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_resources_log";
        }
    }
}
