// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportClothingDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.ClothingDesc> records);
        public event ImportClothingDescHandler? OnImportClothingDesc;

        public void ImportClothingDesc(System.Collections.Generic.List<BitCraft.Spacetime.ClothingDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportClothingDesc(records));
        }

        public bool InvokeImportClothingDesc(ReducerEventContext ctx, Reducer.ImportClothingDesc args)
        {
            if (OnImportClothingDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportClothingDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportClothingDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ClothingDesc> Records;

            public ImportClothingDesc(System.Collections.Generic.List<ClothingDesc> Records)
            {
                this.Records = Records;
            }

            public ImportClothingDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_clothing_desc";
        }
    }
}
