// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportActiveBuffStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.ActiveBuffState> records);
        public event ImportActiveBuffStateHandler? OnImportActiveBuffState;

        public void ImportActiveBuffState(System.Collections.Generic.List<BitCraft.Spacetime.ActiveBuffState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportActiveBuffState(records));
        }

        public bool InvokeImportActiveBuffState(ReducerEventContext ctx, Reducer.ImportActiveBuffState args)
        {
            if (OnImportActiveBuffState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportActiveBuffState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportActiveBuffState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ActiveBuffState> Records;

            public ImportActiveBuffState(System.Collections.Generic.List<ActiveBuffState> Records)
            {
                this.Records = Records;
            }

            public ImportActiveBuffState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_active_buff_state";
        }
    }
}
