// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InsertResourcesLogHandler(ReducerEventContext ctx, BitCraft.Spacetime.ResourcesLog resourcesLog);
        public event InsertResourcesLogHandler? OnInsertResourcesLog;

        public void InsertResourcesLog(BitCraft.Spacetime.ResourcesLog resourcesLog)
        {
            conn.InternalCallReducer(new Reducer.InsertResourcesLog(resourcesLog));
        }

        public bool InvokeInsertResourcesLog(ReducerEventContext ctx, Reducer.InsertResourcesLog args)
        {
            if (OnInsertResourcesLog == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInsertResourcesLog(
                ctx,
                args.ResourcesLog
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InsertResourcesLog : Reducer, IReducerArgs
        {
            [DataMember(Name = "resources_log")]
            public ResourcesLog ResourcesLog;

            public InsertResourcesLog(ResourcesLog ResourcesLog)
            {
                this.ResourcesLog = ResourcesLog;
            }

            public InsertResourcesLog()
            {
                this.ResourcesLog = new();
            }

            string IReducerArgs.ReducerName => "insert_resources_log";
        }
    }
}
