// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ItemPickUpHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerDroppedInventoryPickUpRequest request);
        public event ItemPickUpHandler? OnItemPickUp;

        public void ItemPickUp(BitCraft.Spacetime.PlayerDroppedInventoryPickUpRequest request)
        {
            conn.InternalCallReducer(new Reducer.ItemPickUp(request));
        }

        public bool InvokeItemPickUp(ReducerEventContext ctx, Reducer.ItemPickUp args)
        {
            if (OnItemPickUp == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnItemPickUp(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ItemPickUp : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerDroppedInventoryPickUpRequest Request;

            public ItemPickUp(PlayerDroppedInventoryPickUpRequest Request)
            {
                this.Request = Request;
            }

            public ItemPickUp()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "item_pick_up";
        }
    }
}
