// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ItemStackMoveHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerItemStackMoveRequest request);
        public event ItemStackMoveHandler? OnItemStackMove;

        public void ItemStackMove(BitCraft.Spacetime.PlayerItemStackMoveRequest request)
        {
            conn.InternalCallReducer(new Reducer.ItemStackMove(request));
        }

        public bool InvokeItemStackMove(ReducerEventContext ctx, Reducer.ItemStackMove args)
        {
            if (OnItemStackMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnItemStackMove(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ItemStackMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerItemStackMoveRequest Request;

            public ItemStackMove(PlayerItemStackMoveRequest Request)
            {
                this.Request = Request;
            }

            public ItemStackMove()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "item_stack_move";
        }
    }
}
