// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ItemUseStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerItemUseRequest request);
        public event ItemUseStartHandler? OnItemUseStart;

        public void ItemUseStart(BitCraft.Spacetime.PlayerItemUseRequest request)
        {
            conn.InternalCallReducer(new Reducer.ItemUseStart(request));
        }

        public bool InvokeItemUseStart(ReducerEventContext ctx, Reducer.ItemUseStart args)
        {
            if (OnItemUseStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnItemUseStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ItemUseStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerItemUseRequest Request;

            public ItemUseStart(PlayerItemUseRequest Request)
            {
                this.Request = Request;
            }

            public ItemUseStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "item_use_start";
        }
    }
}
