// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ItemConvertHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerItemConvertRequest request);
        public event ItemConvertHandler? OnItemConvert;

        public void ItemConvert(BitCraft.Spacetime.PlayerItemConvertRequest request)
        {
            conn.InternalCallReducer(new Reducer.ItemConvert(request));
        }

        public bool InvokeItemConvert(ReducerEventContext ctx, Reducer.ItemConvert args)
        {
            if (OnItemConvert == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnItemConvert(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ItemConvert : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerItemConvertRequest Request;

            public ItemConvert(PlayerItemConvertRequest Request)
            {
                this.Request = Request;
            }

            public ItemConvert()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "item_convert";
        }
    }
}
