// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ItemUseHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerItemUseRequest request);
        public event ItemUseHandler? OnItemUse;

        public void ItemUse(BitCraft.Spacetime.PlayerItemUseRequest request)
        {
            conn.InternalCallReducer(new Reducer.ItemUse(request));
        }

        public bool InvokeItemUse(ReducerEventContext ctx, Reducer.ItemUse args)
        {
            if (OnItemUse == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnItemUse(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ItemUse : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerItemUseRequest Request;

            public ItemUse(PlayerItemUseRequest Request)
            {
                this.Request = Request;
            }

            public ItemUse()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "item_use";
        }
    }
}
