// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OrderCollectHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerOrderCollectRequest request);
        public event OrderCollectHandler? OnOrderCollect;

        public void OrderCollect(BitCraft.Spacetime.PlayerOrderCollectRequest request)
        {
            conn.InternalCallReducer(new Reducer.OrderCollect(request));
        }

        public bool InvokeOrderCollect(ReducerEventContext ctx, Reducer.OrderCollect args)
        {
            if (OnOrderCollect == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOrderCollect(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OrderCollect : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerOrderCollectRequest Request;

            public OrderCollect(PlayerOrderCollectRequest Request)
            {
                this.Request = Request;
            }

            public OrderCollect()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "order_collect";
        }
    }
}
