// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void OrderCancelHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerOrderCancelRequest request);
        public event OrderCancelHandler? OnOrderCancel;

        public void OrderCancel(BitCraft.Spacetime.PlayerOrderCancelRequest request)
        {
            conn.InternalCallReducer(new Reducer.OrderCancel(request));
        }

        public bool InvokeOrderCancel(ReducerEventContext ctx, Reducer.OrderCancel args)
        {
            if (OnOrderCancel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnOrderCancel(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class OrderCancel : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerOrderCancelRequest Request;

            public OrderCancel(PlayerOrderCancelRequest Request)
            {
                this.Request = Request;
            }

            public OrderCancel()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "order_cancel";
        }
    }
}
