// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PavingDestroyTileHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPavingDestroyTileRequest request);
        public event PavingDestroyTileHandler? OnPavingDestroyTile;

        public void PavingDestroyTile(BitCraft.Spacetime.PlayerPavingDestroyTileRequest request)
        {
            conn.InternalCallReducer(new Reducer.PavingDestroyTile(request));
        }

        public bool InvokePavingDestroyTile(ReducerEventContext ctx, Reducer.PavingDestroyTile args)
        {
            if (OnPavingDestroyTile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPavingDestroyTile(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PavingDestroyTile : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPavingDestroyTileRequest Request;

            public PavingDestroyTile(PlayerPavingDestroyTileRequest Request)
            {
                this.Request = Request;
            }

            public PavingDestroyTile()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "paving_destroy_tile";
        }
    }
}
