// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PermissionEditHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPermissionEditRequest request);
        public event PermissionEditHandler? OnPermissionEdit;

        public void PermissionEdit(BitCraft.Spacetime.PlayerPermissionEditRequest request)
        {
            conn.InternalCallReducer(new Reducer.PermissionEdit(request));
        }

        public bool InvokePermissionEdit(ReducerEventContext ctx, Reducer.PermissionEdit args)
        {
            if (OnPermissionEdit == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPermissionEdit(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PermissionEdit : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPermissionEditRequest Request;

            public PermissionEdit(PlayerPermissionEditRequest Request)
            {
                this.Request = Request;
            }

            public PermissionEdit()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "permission_edit";
        }
    }
}
