// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PillarShapingDestroyStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPillarShapingDestroyRequest request);
        public event PillarShapingDestroyStartHandler? OnPillarShapingDestroyStart;

        public void PillarShapingDestroyStart(BitCraft.Spacetime.PlayerPillarShapingDestroyRequest request)
        {
            conn.InternalCallReducer(new Reducer.PillarShapingDestroyStart(request));
        }

        public bool InvokePillarShapingDestroyStart(ReducerEventContext ctx, Reducer.PillarShapingDestroyStart args)
        {
            if (OnPillarShapingDestroyStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPillarShapingDestroyStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PillarShapingDestroyStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPillarShapingDestroyRequest Request;

            public PillarShapingDestroyStart(PlayerPillarShapingDestroyRequest Request)
            {
                this.Request = Request;
            }

            public PillarShapingDestroyStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "pillar_shaping_destroy_start";
        }
    }
}
