// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PillarShapingPlacePillarHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPillarShapingPlaceRequest request);
        public event PillarShapingPlacePillarHandler? OnPillarShapingPlacePillar;

        public void PillarShapingPlacePillar(BitCraft.Spacetime.PlayerPillarShapingPlaceRequest request)
        {
            conn.InternalCallReducer(new Reducer.PillarShapingPlacePillar(request));
        }

        public bool InvokePillarShapingPlacePillar(ReducerEventContext ctx, Reducer.PillarShapingPlacePillar args)
        {
            if (OnPillarShapingPlacePillar == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPillarShapingPlacePillar(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PillarShapingPlacePillar : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPillarShapingPlaceRequest Request;

            public PillarShapingPlacePillar(PlayerPillarShapingPlaceRequest Request)
            {
                this.Request = Request;
            }

            public PillarShapingPlacePillar()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "pillar_shaping_place_pillar";
        }
    }
}
