// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceableInteractHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPlaceableInteractRequest request);
        public event PlaceableInteractHandler? OnPlaceableInteract;

        public void PlaceableInteract(BitCraft.Spacetime.PlayerPlaceableInteractRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlaceableInteract(request));
        }

        public bool InvokePlaceableInteract(ReducerEventContext ctx, Reducer.PlaceableInteract args)
        {
            if (OnPlaceableInteract == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceableInteract(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceableInteract : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPlaceableInteractRequest Request;

            public PlaceableInteract(PlayerPlaceableInteractRequest Request)
            {
                this.Request = Request;
            }

            public PlaceableInteract()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "placeable_interact";
        }
    }
}
