// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceablePlaceStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPlaceablePlaceRequest request);
        public event PlaceablePlaceStartHandler? OnPlaceablePlaceStart;

        public void PlaceablePlaceStart(BitCraft.Spacetime.PlayerPlaceablePlaceRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlaceablePlaceStart(request));
        }

        public bool InvokePlaceablePlaceStart(ReducerEventContext ctx, Reducer.PlaceablePlaceStart args)
        {
            if (OnPlaceablePlaceStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceablePlaceStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceablePlaceStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPlaceablePlaceRequest Request;

            public PlaceablePlaceStart(PlayerPlaceablePlaceRequest Request)
            {
                this.Request = Request;
            }

            public PlaceablePlaceStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "placeable_place_start";
        }
    }
}
