// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlaceableInteractStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerPlaceableInteractRequest request);
        public event PlaceableInteractStartHandler? OnPlaceableInteractStart;

        public void PlaceableInteractStart(BitCraft.Spacetime.PlayerPlaceableInteractRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlaceableInteractStart(request));
        }

        public bool InvokePlaceableInteractStart(ReducerEventContext ctx, Reducer.PlaceableInteractStart args)
        {
            if (OnPlaceableInteractStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlaceableInteractStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlaceableInteractStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerPlaceableInteractRequest Request;

            public PlaceableInteractStart(PlayerPlaceableInteractRequest Request)
            {
                this.Request = Request;
            }

            public PlaceableInteractStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "placeable_interact_start";
        }
    }
}
