// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerHousingEnterHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerHousingEnterRequest request);
        public event PlayerHousingEnterHandler? OnPlayerHousingEnter;

        public void PlayerHousingEnter(BitCraft.Spacetime.PlayerHousingEnterRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerHousingEnter(request));
        }

        public bool InvokePlayerHousingEnter(ReducerEventContext ctx, Reducer.PlayerHousingEnter args)
        {
            if (OnPlayerHousingEnter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerHousingEnter(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerHousingEnter : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerHousingEnterRequest Request;

            public PlayerHousingEnter(PlayerHousingEnterRequest Request)
            {
                this.Request = Request;
            }

            public PlayerHousingEnter()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_housing_enter";
        }
    }
}
