// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerUseElevatorHandler(ReducerEventContext ctx, ulong platformEntityId);
        public event PlayerUseElevatorHandler? OnPlayerUseElevator;

        public void PlayerUseElevator(ulong platformEntityId)
        {
            conn.InternalCallReducer(new Reducer.PlayerUseElevator(platformEntityId));
        }

        public bool InvokePlayerUseElevator(ReducerEventContext ctx, Reducer.PlayerUseElevator args)
        {
            if (OnPlayerUseElevator == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerUseElevator(
                ctx,
                args.PlatformEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerUseElevator : Reducer, IReducerArgs
        {
            [DataMember(Name = "platform_entity_id")]
            public ulong PlatformEntityId;

            public PlayerUseElevator(ulong PlatformEntityId)
            {
                this.PlatformEntityId = PlatformEntityId;
            }

            public PlayerUseElevator()
            {
            }

            string IReducerArgs.ReducerName => "player_use_elevator";
        }
    }
}
