// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerMoveHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerMoveRequest request);
        public event PlayerMoveHandler? OnPlayerMove;

        public void PlayerMove(BitCraft.Spacetime.PlayerMoveRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerMove(request));
        }

        public bool InvokePlayerMove(ReducerEventContext ctx, Reducer.PlayerMove args)
        {
            if (OnPlayerMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerMove(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerMoveRequest Request;

            public PlayerMove(PlayerMoveRequest Request)
            {
                this.Request = Request;
            }

            public PlayerMove()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_move";
        }
    }
}
