// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerCompleteTaskHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerCompleteTaskRequest request);
        public event PlayerCompleteTaskHandler? OnPlayerCompleteTask;

        public void PlayerCompleteTask(BitCraft.Spacetime.PlayerCompleteTaskRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerCompleteTask(request));
        }

        public bool InvokePlayerCompleteTask(ReducerEventContext ctx, Reducer.PlayerCompleteTask args)
        {
            if (OnPlayerCompleteTask == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerCompleteTask(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerCompleteTask : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerCompleteTaskRequest Request;

            public PlayerCompleteTask(PlayerCompleteTaskRequest Request)
            {
                this.Request = Request;
            }

            public PlayerCompleteTask()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_complete_task";
        }
    }
}
