// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerClimbHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerClimbRequest request);
        public event PlayerClimbHandler? OnPlayerClimb;

        public void PlayerClimb(BitCraft.Spacetime.PlayerClimbRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerClimb(request));
        }

        public bool InvokePlayerClimb(ReducerEventContext ctx, Reducer.PlayerClimb args)
        {
            if (OnPlayerClimb == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerClimb(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerClimb : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClimbRequest Request;

            public PlayerClimb(PlayerClimbRequest Request)
            {
                this.Request = Request;
            }

            public PlayerClimb()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_climb";
        }
    }
}
