// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ProjectSiteAdvanceProjectStartHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerProjectSiteAdvanceProjectRequest request);
        public event ProjectSiteAdvanceProjectStartHandler? OnProjectSiteAdvanceProjectStart;

        public void ProjectSiteAdvanceProjectStart(BitCraft.Spacetime.PlayerProjectSiteAdvanceProjectRequest request)
        {
            conn.InternalCallReducer(new Reducer.ProjectSiteAdvanceProjectStart(request));
        }

        public bool InvokeProjectSiteAdvanceProjectStart(ReducerEventContext ctx, Reducer.ProjectSiteAdvanceProjectStart args)
        {
            if (OnProjectSiteAdvanceProjectStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnProjectSiteAdvanceProjectStart(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ProjectSiteAdvanceProjectStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerProjectSiteAdvanceProjectRequest Request;

            public ProjectSiteAdvanceProjectStart(PlayerProjectSiteAdvanceProjectRequest Request)
            {
                this.Request = Request;
            }

            public ProjectSiteAdvanceProjectStart()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "project_site_advance_project_start";
        }
    }
}
