// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ProjectSitePlaceHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerProjectSitePlaceRequest request);
        public event ProjectSitePlaceHandler? OnProjectSitePlace;

        public void ProjectSitePlace(BitCraft.Spacetime.PlayerProjectSitePlaceRequest request)
        {
            conn.InternalCallReducer(new Reducer.ProjectSitePlace(request));
        }

        public bool InvokeProjectSitePlace(ReducerEventContext ctx, Reducer.ProjectSitePlace args)
        {
            if (OnProjectSitePlace == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnProjectSitePlace(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ProjectSitePlace : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerProjectSitePlaceRequest Request;

            public ProjectSitePlace(PlayerProjectSitePlaceRequest Request)
            {
                this.Request = Request;
            }

            public ProjectSitePlace()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "project_site_place";
        }
    }
}
