// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RentPurchaseHandler(ReducerEventContext ctx, BitCraft.Spacetime.RentPurchaseRequest request);
        public event RentPurchaseHandler? OnRentPurchase;

        public void RentPurchase(BitCraft.Spacetime.RentPurchaseRequest request)
        {
            conn.InternalCallReducer(new Reducer.RentPurchase(request));
        }

        public bool InvokeRentPurchase(ReducerEventContext ctx, Reducer.RentPurchase args)
        {
            if (OnRentPurchase == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRentPurchase(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RentPurchase : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public RentPurchaseRequest Request;

            public RentPurchase(RentPurchaseRequest Request)
            {
                this.Request = Request;
            }

            public RentPurchase()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "rent_purchase";
        }
    }
}
