// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RentEvictHandler(ReducerEventContext ctx, BitCraft.Spacetime.RentEvictRequest request);
        public event RentEvictHandler? OnRentEvict;

        public void RentEvict(BitCraft.Spacetime.RentEvictRequest request)
        {
            conn.InternalCallReducer(new Reducer.RentEvict(request));
        }

        public bool InvokeRentEvict(ReducerEventContext ctx, Reducer.RentEvict args)
        {
            if (OnRentEvict == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRentEvict(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RentEvict : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public RentEvictRequest Request;

            public RentEvict(RentEvictRequest Request)
            {
                this.Request = Request;
            }

            public RentEvict()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "rent_evict";
        }
    }
}
