// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RentSetDailyRateHandler(ReducerEventContext ctx, BitCraft.Spacetime.RentSetDailyRateRequest request);
        public event RentSetDailyRateHandler? OnRentSetDailyRate;

        public void RentSetDailyRate(BitCraft.Spacetime.RentSetDailyRateRequest request)
        {
            conn.InternalCallReducer(new Reducer.RentSetDailyRate(request));
        }

        public bool InvokeRentSetDailyRate(ReducerEventContext ctx, Reducer.RentSetDailyRate args)
        {
            if (OnRentSetDailyRate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRentSetDailyRate(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RentSetDailyRate : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public RentSetDailyRateRequest Request;

            public RentSetDailyRate(RentSetDailyRateRequest Request)
            {
                this.Request = Request;
            }

            public RentSetDailyRate()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "rent_set_daily_rate";
        }
    }
}
