// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RentUnlistHandler(ReducerEventContext ctx, BitCraft.Spacetime.RentUnlistRequest request);
        public event RentUnlistHandler? OnRentUnlist;

        public void RentUnlist(BitCraft.Spacetime.RentUnlistRequest request)
        {
            conn.InternalCallReducer(new Reducer.RentUnlist(request));
        }

        public bool InvokeRentUnlist(ReducerEventContext ctx, Reducer.RentUnlist args)
        {
            if (OnRentUnlist == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRentUnlist(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RentUnlist : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public RentUnlistRequest Request;

            public RentUnlist(RentUnlistRequest Request)
            {
                this.Request = Request;
            }

            public RentUnlist()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "rent_unlist";
        }
    }
}
