// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RentAddTenantHandler(ReducerEventContext ctx, BitCraft.Spacetime.RentAddTenantRequest request);
        public event RentAddTenantHandler? OnRentAddTenant;

        public void RentAddTenant(BitCraft.Spacetime.RentAddTenantRequest request)
        {
            conn.InternalCallReducer(new Reducer.RentAddTenant(request));
        }

        public bool InvokeRentAddTenant(ReducerEventContext ctx, Reducer.RentAddTenant args)
        {
            if (OnRentAddTenant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRentAddTenant(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RentAddTenant : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public RentAddTenantRequest Request;

            public RentAddTenant(RentAddTenantRequest Request)
            {
                this.Request = Request;
            }

            public RentAddTenant()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "rent_add_tenant";
        }
    }
}
