// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportEntityHandler(ReducerEventContext ctx, BitCraft.Spacetime.ReportEntityMessage request);
        public event ReportEntityHandler? OnReportEntity;

        public void ReportEntity(BitCraft.Spacetime.ReportEntityMessage request)
        {
            conn.InternalCallReducer(new Reducer.ReportEntity(request));
        }

        public bool InvokeReportEntity(ReducerEventContext ctx, Reducer.ReportEntity args)
        {
            if (OnReportEntity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportEntity(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportEntity : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public ReportEntityMessage Request;

            public ReportEntity(ReportEntityMessage Request)
            {
                this.Request = Request;
            }

            public ReportEntity()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "report_entity";
        }
    }
}
