// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RetrieveLostItemHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerRetrieveLostItemRequest request);
        public event RetrieveLostItemHandler? OnRetrieveLostItem;

        public void RetrieveLostItem(BitCraft.Spacetime.PlayerRetrieveLostItemRequest request)
        {
            conn.InternalCallReducer(new Reducer.RetrieveLostItem(request));
        }

        public bool InvokeRetrieveLostItem(ReducerEventContext ctx, Reducer.RetrieveLostItem args)
        {
            if (OnRetrieveLostItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRetrieveLostItem(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RetrieveLostItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerRetrieveLostItemRequest Request;

            public RetrieveLostItem(PlayerRetrieveLostItemRequest Request)
            {
                this.Request = Request;
            }

            public RetrieveLostItem()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "retrieve_lost_item";
        }
    }
}
