// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetHomeHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerSetHomeRequest request);
        public event SetHomeHandler? OnSetHome;

        public void SetHome(BitCraft.Spacetime.PlayerSetHomeRequest request)
        {
            conn.InternalCallReducer(new Reducer.SetHome(request));
        }

        public bool InvokeSetHome(ReducerEventContext ctx, Reducer.SetHome args)
        {
            if (OnSetHome == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetHome(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetHome : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerSetHomeRequest Request;

            public SetHome(PlayerSetHomeRequest Request)
            {
                this.Request = Request;
            }

            public SetHome()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "set_home";
        }
    }
}
