// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SignInHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerSignInRequest request);
        public event SignInHandler? OnSignIn;

        public void SignIn(BitCraft.Spacetime.PlayerSignInRequest request)
        {
            conn.InternalCallReducer(new Reducer.SignIn(request));
        }

        public bool InvokeSignIn(ReducerEventContext ctx, Reducer.SignIn args)
        {
            if (OnSignIn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSignIn(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SignIn : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerSignInRequest Request;

            public SignIn(PlayerSignInRequest Request)
            {
                this.Request = Request;
            }

            public SignIn()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "sign_in";
        }
    }
}
