// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageEnemyScalingDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.EnemyScalingDesc> records);
        public event StageEnemyScalingDescHandler? OnStageEnemyScalingDesc;

        public void StageEnemyScalingDesc(System.Collections.Generic.List<BitCraft.Spacetime.EnemyScalingDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageEnemyScalingDesc(records));
        }

        public bool InvokeStageEnemyScalingDesc(ReducerEventContext ctx, Reducer.StageEnemyScalingDesc args)
        {
            if (OnStageEnemyScalingDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageEnemyScalingDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageEnemyScalingDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EnemyScalingDesc> Records;

            public StageEnemyScalingDesc(System.Collections.Generic.List<EnemyScalingDesc> Records)
            {
                this.Records = Records;
            }

            public StageEnemyScalingDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_enemy_scaling_desc";
        }
    }
}
