// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StagePlaceableDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.PlaceableDesc> records);
        public event StagePlaceableDescHandler? OnStagePlaceableDesc;

        public void StagePlaceableDesc(System.Collections.Generic.List<BitCraft.Spacetime.PlaceableDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StagePlaceableDesc(records));
        }

        public bool InvokeStagePlaceableDesc(ReducerEventContext ctx, Reducer.StagePlaceableDesc args)
        {
            if (OnStagePlaceableDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStagePlaceableDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StagePlaceableDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<PlaceableDesc> Records;

            public StagePlaceableDesc(System.Collections.Generic.List<PlaceableDesc> Records)
            {
                this.Records = Records;
            }

            public StagePlaceableDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_placeable_desc";
        }
    }
}
