// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageStageRewardsDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.StageRewardsDesc> records);
        public event StageStageRewardsDescHandler? OnStageStageRewardsDesc;

        public void StageStageRewardsDesc(System.Collections.Generic.List<BitCraft.Spacetime.StageRewardsDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageStageRewardsDesc(records));
        }

        public bool InvokeStageStageRewardsDesc(ReducerEventContext ctx, Reducer.StageStageRewardsDesc args)
        {
            if (OnStageStageRewardsDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageStageRewardsDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageStageRewardsDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<StageRewardsDesc> Records;

            public StageStageRewardsDesc(System.Collections.Generic.List<StageRewardsDesc> Records)
            {
                this.Records = Records;
            }

            public StageStageRewardsDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_stage_rewards_desc";
        }
    }
}
