// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageEnemyDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<BitCraft.Spacetime.EnemyDesc> records);
        public event StageEnemyDescHandler? OnStageEnemyDesc;

        public void StageEnemyDesc(System.Collections.Generic.List<BitCraft.Spacetime.EnemyDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageEnemyDesc(records));
        }

        public bool InvokeStageEnemyDesc(ReducerEventContext ctx, Reducer.StageEnemyDesc args)
        {
            if (OnStageEnemyDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageEnemyDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageEnemyDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EnemyDesc> Records;

            public StageEnemyDesc(System.Collections.Generic.List<EnemyDesc> Records)
            {
                this.Records = Records;
            }

            public StageEnemyDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_enemy_desc";
        }
    }
}
