// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TargetUpdateHandler(ReducerEventContext ctx, BitCraft.Spacetime.TargetUpdateRequest request);
        public event TargetUpdateHandler? OnTargetUpdate;

        public void TargetUpdate(BitCraft.Spacetime.TargetUpdateRequest request)
        {
            conn.InternalCallReducer(new Reducer.TargetUpdate(request));
        }

        public bool InvokeTargetUpdate(ReducerEventContext ctx, Reducer.TargetUpdate args)
        {
            if (OnTargetUpdate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTargetUpdate(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TargetUpdate : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public TargetUpdateRequest Request;

            public TargetUpdate(TargetUpdateRequest Request)
            {
                this.Request = Request;
            }

            public TargetUpdate()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "target_update";
        }
    }
}
