// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TerraformHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerTerraformRequest request);
        public event TerraformHandler? OnTerraform;

        public void Terraform(BitCraft.Spacetime.PlayerTerraformRequest request)
        {
            conn.InternalCallReducer(new Reducer.Terraform(request));
        }

        public bool InvokeTerraform(ReducerEventContext ctx, Reducer.Terraform args)
        {
            if (OnTerraform == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTerraform(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Terraform : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerTerraformRequest Request;

            public Terraform(PlayerTerraformRequest Request)
            {
                this.Request = Request;
            }

            public Terraform()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "terraform";
        }
    }
}
