// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeAcceptHandler(ReducerEventContext ctx, BitCraft.Spacetime.PlayerTradeAcceptRequest request);
        public event TradeAcceptHandler? OnTradeAccept;

        public void TradeAccept(BitCraft.Spacetime.PlayerTradeAcceptRequest request)
        {
            conn.InternalCallReducer(new Reducer.TradeAccept(request));
        }

        public bool InvokeTradeAccept(ReducerEventContext ctx, Reducer.TradeAccept args)
        {
            if (OnTradeAccept == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeAccept(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeAccept : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerTradeAcceptRequest Request;

            public TradeAccept(PlayerTradeAcceptRequest Request)
            {
                this.Request = Request;
            }

            public TradeAccept()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "trade_accept";
        }
    }
}
