// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Spacetime
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void WorldPlaceResourceHandler(ReducerEventContext ctx, BitCraft.Spacetime.WorldPlaceResourceRequest request);
        public event WorldPlaceResourceHandler? OnWorldPlaceResource;

        public void WorldPlaceResource(BitCraft.Spacetime.WorldPlaceResourceRequest request)
        {
            conn.InternalCallReducer(new Reducer.WorldPlaceResource(request));
        }

        public bool InvokeWorldPlaceResource(ReducerEventContext ctx, Reducer.WorldPlaceResource args)
        {
            if (OnWorldPlaceResource == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnWorldPlaceResource(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class WorldPlaceResource : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public WorldPlaceResourceRequest Request;

            public WorldPlaceResource(WorldPlaceResourceRequest Request)
            {
                this.Request = Request;
            }

            public WorldPlaceResource()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "world_place_resource";
        }
    }
}
