// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace BitCraft.Global
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingMapIconDesc
    {
        [DataMember(Name = "building_id")]
        public int BuildingId;
        [DataMember(Name = "icon_address")]
        public string IconAddress;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "text")]
        public string Text;

        public BuildingMapIconDesc(
            int BuildingId,
            string IconAddress,
            string Title,
            string Text
        )
        {
            this.BuildingId = BuildingId;
            this.IconAddress = IconAddress;
            this.Title = Title;
            this.Text = Text;
        }

        public BuildingMapIconDesc()
        {
            this.IconAddress = "";
            this.Title = "";
            this.Text = "";
        }
    }
}
